
version: '2'

services:
  rds:
    image: redis:3.2.11
    # ports: 
      # - 6379:6379
    restart: always
  iserv:
    build: ./conf.d
    image: iserv:3.5
    volumes:
      - ./:/usr/src/myapp
    ports: 
      - 83:80
    command: python3 /usr/src/myapp/app.py
    depends_on:
      - rds
    restart: always