
version: '3'

services:
  rds:
    image: redis:3.2.11-alpine
    container_name: pyimgservrds
    restart: always
  iserv:
    build: .
    image: pyimgserv
    container_name: pyimgserv
    volumes:
      - ./:/usr/src/app
    ports: 
      - "0.0.0.0:27101:80"
    command: "python3 /usr/src/app/app.py"
    depends_on:
      - rds
    restart: always
